import ThemeDialog from '@/components/theme-dialog/index'
import initLoginInfo from '@/config/token.js'
import { setLoginInfo, getLoginInfo } from '@/utils/secret-key'
import { getLoginProfileInfo } from '@/components/theme-login/store/actionCreator'
import { addPlaylistId, getCurrentSongIndex, getPlaylistId, initCurrentSongIndex } from '../../utils/localstorage'
import { SONG_PLAYLIST_ID as songplaylistId } from '@/common/constants'
import { getSongDetailArrayAction } from '../../hooks/change-state'